services:
  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "${APP_PORT:-127.0.0.1:80}:80"
    environment:
      - API_SERVICE_NAME=frontend
    networks:
      - frontend

networks:
  frontend: {}
  
